name: iminpaint
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - astroid=2.2.5
  - attrs=19.1.0
  - backcall=0.1.0
  - blas=1.0
  - bleach=3.1.0
  - bzip2=1.0.8
  - ca-certificates=2019.5.15
  - cairo=1.16.0
  - certifi=2019.6.16
  - cffi=1.12.3
  - cloudpickle=1.2.1
  - cudatoolkit=9.2
  - cycler=0.10.0
  - cytoolz=0.10.0
  - dask-core=2.3.0
  - dbus=1.13.6
  - decorator=4.4.0
  - defusedxml=0.6.0
  - entrypoints=0.3
  - expat=2.2.6
  - ffmpeg=4.1.3
  - fontconfig=2.13.1
  - freetype=2.9.1
  - gettext=0.19.8.1
  - giflib=5.1.9
  - glib=2.58.3
  - gmp=6.1.2
  - gnutls=3.6.5
  - graphite2=1.3.13
  - gst-plugins-base=1.14.5
  - gstreamer=1.14.5
  - harfbuzz=2.4.0
  - hdf5=1.10.5
  - icu=58.2
  - imageio=2.5.0
  - intel-openmp=2019.4
  - ipykernel=5.1.2
  - ipython=7.8.0
  - ipython_genutils=0.2.0
  - isort=4.3.21
  - jasper=1.900.1
  - jedi=0.15.1
  - jinja2=2.10.1
  - jpeg=9c
  - json5=0.8.5
  - jsonschema=3.0.2
  - jupyter_client=5.3.1
  - jupyter_core=4.5.0
  - jupyterlab=1.1.1
  - jupyterlab_server=1.0.0
  - kiwisolver=1.1.0
  - lame=3.100
  - lazy-object-proxy=1.4.2
  - libblas=3.8.0
  - libcblas=3.8.0
  - libedit=3.1.20181209
  - libffi=3.2.1
  - libgcc-ng=9.1.0
  - libgfortran-ng=7.3.0
  - libiconv=1.15
  - liblapack=3.8.0
  - liblapacke=3.8.0
  - libpng=1.6.37
  - libsodium=1.0.16
  - libstdcxx-ng=9.1.0
  - libtiff=4.0.10
  - libuuid=2.32.1
  - libwebp=1.0.2
  - libxcb=1.13
  - libxml2=2.9.9
  - markupsafe=1.1.1
  - matplotlib=3.1.1
  - mccabe=0.6.1
  - mistune=0.8.4
  - mkl=2019.4
  - mkl-service=2.3.0
  - mkl_fft=1.0.14
  - mkl_random=1.0.2
  - nb_conda=2.2.1
  - nb_conda_kernels=2.2.2
  - nbconvert=5.5.0
  - nbformat=4.4.0
  - ncurses=6.1
  - nettle=3.4.1
  - networkx=2.3
  - ninja=1.9.0
  - notebook=6.0.0
  - numpy=1.16.4
  - numpy-base=1.16.4
  - olefile=0.46
  - opencv=4.1.0
  - openh264=1.8.0
  - openssl=1.1.1c
  - pandas=0.25.0
  - pandoc=2.2.3.2
  - pandocfilters=1.4.2
  - parso=0.5.1
  - pcre=8.43
  - pexpect=4.7.0
  - pickleshare=0.7.5
  - pillow=6.1.0
  - pip=19.2.2
  - pixman=0.38.0
  - prometheus_client=0.7.1
  - prompt_toolkit=2.0.9
  - ptyprocess=0.6.0
  - pycparser=2.19
  - pygments=2.4.2
  - pylint=2.3.1
  - pyparsing=2.4.2
  - pyqt=5.9.2
  - pyrsistent=0.14.11
  - python=3.7.4
  - python-dateutil=2.8.0
  - pytorch=1.2.0
  - pytz=2019.2
  - pywavelets=1.0.3
  - pyzmq=18.1.0
  - qt=5.9.7
  - readline=7.0
  - scikit-image=0.15.0
  - scipy=1.3.1
  - send2trash=1.5.0
  - setuptools=41.0.1
  - sip=4.19.8
  - sqlite=3.29.0
  - terminado=0.8.2
  - testpath=0.4.2
  - tk=8.6.8
  - toolz=0.10.0
  - torchvision=0.4.0
  - tornado=6.0.3
  - tqdm=4.32.1
  - traitlets=4.3.2
  - wcwidth=0.1.7
  - webencodings=0.5.1
  - wheel=0.33.4
  - wrapt=1.11.2
  - x264=1!152.20180806
  - xorg-kbproto=1.0.7
  - xorg-libice=1.0.10
  - xorg-libsm=1.2.3
  - xorg-libx11=1.6.8
  - xorg-libxext=1.3.4
  - xorg-libxrender=0.9.10
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.4
  - zeromq=4.3.1
  - zlib=1.2.11
  - zstd=1.3.7
  - pip:
    - chardet==3.0.4
    - flickrapi==2.4.0
    - idna==2.8
    - oauthlib==3.1.0
    - requests==2.22.0
    - requests-oauthlib==1.2.0
    - requests-toolbelt==0.9.1
    - six==1.12.0
    - urllib3==1.25.3
    - wget==3.2
